// Tests for the parts of the SMS code that have no database behind them.
//
// Three of these matter more than the rest:
//
//   * the webhook signature check, verified against the Standard Webhooks
//     specification's own published vector rather than against itself — a
//     verifier that agrees with its own maths is worth nothing
//   * the STOP keyword matcher, because missing one is the failure with a
//     regulator attached
//   * the segment counter, because a single curly apostrophe silently
//     doubles what every message costs
//
// The module under test imports followUps.mjs for its Supabase helper, which
// is bundled with that import stubbed so nothing here can reach the network.
import { build } from "esbuild";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const stub = {
  name: "stub",
  setup(b) {
    b.onResolve({ filter: /followUps\.mjs$/ }, (a) => ({ path: a.path, namespace: "fu" }));
    b.onLoad({ filter: /.*/, namespace: "fu" }, () => ({
      // Routed through a global so a test can make the database fail in a
      // specific way. rpc() throws — that is the behaviour sendSms has to
      // survive — so the default is a throw too.
      contents:
        "export async function rpc(fn, args) { " +
        "  if (globalThis.__rpc) return globalThis.__rpc(fn, args); " +
        "  throw new Error('no network in tests'); }",
      loader: "js",
    }));
  },
};

const dir = mkdtempSync(join(tmpdir(), "smsjs-"));
const out = "verify/.sms-js-bundle.mjs";

await build({
  entryPoints: [join(dir, "entry.js")],
  bundle: true,
  format: "esm",
  platform: "node",
  outfile: out,
  plugins: [
    {
      name: "entry",
      setup(b) {
        b.onResolve({ filter: /entry\.js$/ }, (a) => ({ path: a.path, namespace: "e" }));
        b.onLoad({ filter: /.*/, namespace: "e" }, () => ({
          contents: `
            export * from "${process.cwd()}/netlify/lib/sms.mjs";
            export { signatureValid, keyword, readEvent } from "${process.cwd()}/netlify/functions/sms-inbound.mjs";
          `,
          loader: "js",
          resolveDir: process.cwd(),
        }));
      },
    },
    stub,
  ],
  logLevel: "warning",
});

const M = await import("./.sms-js-bundle.mjs");

let bad = 0;
const chk = (what, pass, detail = "") => {
  if (pass) console.log(`ok    ${what}`);
  else {
    console.log(`FAIL  ${what}${detail ? ` — ${detail}` : ""}`);
    bad++;
  }
};

// --- the webhook signature, against the Standard Webhooks published vector -
//
// Quo signs with Standard Webhooks, and the test vector below is the one
// published in that specification — not one generated by this code. Matching
// a vector we did not produce is the only way to know the implementation
// agrees with the spec rather than merely with itself.
{
  const secret = "whsec_MfKQ9r8GKYqrTwjUPD8ILPZIo2LaLaSw";
  const id = "msg_p5jXN8AQM9LWM0D4loKWxJek";
  const timestamp = "1614265330";
  const body = '{"test": 2432232314}';
  const good = "v1,g0hM9SsE+OTPJTGt/tmIKtSyZlE3uFJELVlNIOLJ1OE=";

  // The vector's timestamp is from 2021, so the replay guard would reject it
  // on its own merits. `now` is injected to hold the clock at that moment —
  // which is also what makes the replay guard itself testable below.
  const now = Number(timestamp) * 1000;
  const base = { id, timestamp, body, secret, now };

  chk(
    "THE POINT: the signature check matches the published Standard Webhooks vector",
    M.signatureValid({ ...base, header: good }),
    "did not validate a signature the specification says is correct"
  );

  chk(
    "a tampered body invalidates the signature",
    !M.signatureValid({ ...base, body: '{"test": 9999999999}', header: good })
  );

  chk(
    "a different message id invalidates the signature",
    !M.signatureValid({ ...base, id: "msg_somethingelse", header: good })
  );

  chk(
    "a different timestamp invalidates the signature",
    !M.signatureValid({ ...base, timestamp: "1614265331", header: good })
  );

  chk(
    "the wrong secret invalidates the signature",
    !M.signatureValid({ ...base, secret: "whsec_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", header: good })
  );

  // Rotation: the header carries a space-delimited list so an old and a new
  // key can both be live. Any one matching is a pass.
  chk(
    "a signature list from a key rotation still validates",
    M.signatureValid({ ...base, header: `v1,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= ${good}` })
  );

  chk(
    "an unknown signature version is ignored, not trusted",
    !M.signatureValid({ ...base, header: good.replace("v1,", "v9,") })
  );

  // THE REPLAY GUARD. Without it, one captured request can be resent
  // tomorrow — and the request worth capturing is somebody's STOP.
  chk(
    "THE POINT: a correctly signed request from an hour ago is refused",
    !M.signatureValid({ ...base, header: good, now: now + 3600 * 1000 }),
    "a captured request could be replayed"
  );

  chk(
    "a request a few seconds old is still accepted",
    M.signatureValid({ ...base, header: good, now: now + 30 * 1000 })
  );

  // The forgeries that matter: nothing at all in any one of the slots must
  // ever be a pass-through.
  chk("a missing signature is refused", !M.signatureValid({ ...base, header: null }));
  chk("a missing secret is refused", !M.signatureValid({ ...base, header: good, secret: null }));
  chk("a missing id is refused", !M.signatureValid({ ...base, id: null, header: good }));
  chk("a missing timestamp is refused", !M.signatureValid({ ...base, timestamp: null, header: good }));
  chk("a non-numeric timestamp is refused", !M.signatureValid({ ...base, timestamp: "soon", header: good }));

  // A short signature must not throw. timingSafeEqual raises on a length
  // mismatch, and a 500 here is something Quo retries.
  let threw = false;
  try {
    M.signatureValid({ ...base, header: "v1,x" });
  } catch {
    threw = true;
  }
  chk("a malformed signature is refused without throwing", !threw);
}

// --- reading the payload ----------------------------------------------------
{
  const inbound = {
    type: "message.received",
    data: {
      object: {
        id: "AC123",
        from: "+15415550101",
        to: ["+15417303593"],
        text: "Sounds good",
        direction: "incoming",
      },
    },
  };
  const evt = M.readEvent(inbound);
  chk("an inbound message yields its sender and text",
    evt.from === "+15415550101" && evt.body === "Sounds good" && evt.id === "AC123",
    JSON.stringify(evt));

  // Quo sends outbound copies and receipts through the same hook. Treating
  // one as a reply would write the CRM's own message onto the customer's
  // history as though they had said it.
  chk("an outbound copy is recognisable and ignorable",
    M.readEvent({ type: "message.delivered", data: { object: { direction: "outgoing" } } }).direction
      === "outgoing");

  // Shapes the docs do not promise. Worth surviving: this payload belongs to
  // somebody else and changed once already when OpenPhone became Quo.
  chk("a flatter payload shape still yields a sender",
    M.readEvent({ type: "message.received", data: { from: "+15415550102", body: "hi" } }).from
      === "+15415550102");
  chk("an empty payload does not throw",
    M.readEvent({}).from === null && M.readEvent(null).from === null);
}

// --- the carrier keywords ---------------------------------------------------
{
  for (const word of ["STOP", "stop", "Stop.", "STOP!", " stop ", "UNSUBSCRIBE", "Cancel", "quit", "END", "StopAll"]) {
    chk(`"${word}" is understood as STOP`, M.keyword(word) === "stop", M.keyword(word) || "null");
  }
  for (const word of ["START", "unstop", "Yes"]) {
    chk(`"${word}" is understood as START`, M.keyword(word) === "start");
  }
  chk('"HELP" is understood as HELP', M.keyword("HELP") === "help");

  // The other side of the rule: an ordinary reply must NOT be swallowed as a
  // keyword, or a customer saying "stop by around 3" gets unsubscribed.
  for (const word of ["stop by around 3", "can you cancel tuesday", "yes please, 2pm works", "no thanks"]) {
    chk(`"${word}" is a normal reply, not a keyword`, M.keyword(word) === null, M.keyword(word) || "null");
  }
}

// --- GSM-7 and what a message costs -----------------------------------------
{
  chk("an em dash is folded to a hyphen", M.gsmSafe("a — b") === "a - b", M.gsmSafe("a — b"));
  chk("curly quotes are straightened", M.gsmSafe("Here’s “it”") === `Here's "it"`, M.gsmSafe("Here’s “it”"));
  chk("an ellipsis becomes three dots", M.gsmSafe("wait…") === "wait...");
  chk("a non-breaking space becomes a space", M.gsmSafe("a b") === "a b");

  chk(
    "plain text counts as one GSM-7 segment",
    M.segmentsFor("Hello there").segments === 1 &&
      M.segmentsFor("Hello there").encoding === "GSM-7"
  );

  // THE REASON gsmSafe EXISTS. One curly apostrophe drops the segment size
  // from 160 characters to 70, so a message that fitted in one now costs
  // two — and the customer's phone may show it as two notifications.
  {
    const withCurly = "Here’s your quote from Sky Blue Cleaning, screens and sills included, accept it here please";
    const straight = M.gsmSafe(withCurly);
    const before = M.segmentsFor(withCurly);
    const after = M.segmentsFor(straight);
    chk(
      "THE POINT: one curly apostrophe would have cost an extra segment",
      before.encoding === "UCS-2" && before.segments > after.segments && after.segments === 1,
      `${before.encoding} ${before.segments} seg -> ${after.encoding} ${after.segments} seg`
    );
  }

  chk(
    "the GSM-7 boundary is at 160, not 161",
    M.segmentsFor("a".repeat(160)).segments === 1 &&
      M.segmentsFor("a".repeat(161)).segments === 2,
    `${M.segmentsFor("a".repeat(160)).segments} / ${M.segmentsFor("a".repeat(161)).segments}`
  );

  // The extension characters cost two septets each, which is why 80 of them
  // overflow a 160-character segment.
  chk(
    "an extension character costs two septets",
    M.segmentsFor("[".repeat(80)).segments === 1 &&
      M.segmentsFor("[".repeat(81)).segments === 2
  );

  chk("an emoji forces UCS-2", M.segmentsFor("hi 👋").encoding === "UCS-2");
}

// --- the messages themselves ------------------------------------------------
{
  const token = "a".repeat(64);

  const quote = M.quoteSms({ customerName: "Karen Emery", amount: 475, token });
  chk("the quote text uses the first name only", quote.includes("Hey Karen,") && !quote.includes("Emery"));
  chk("the quote text shows whole dollars", quote.includes("$475") && !quote.includes("475.00"), quote);
  chk("the quote text carries the link", quote.includes(`/q/${token}`));
  chk("the quote text tells them how to opt out", /reply stop/i.test(quote));
  chk(
    "the quote text is GSM-7, so it is billed at 160 per segment",
    M.segmentsFor(quote).encoding === "GSM-7",
    M.segmentsFor(quote).encoding
  );

  const unopened = M.nudgeUnopenedSms({ customerName: "Karen", amount: 475, token });
  const opened = M.nudgeOpenedSms({ customerName: "Karen", amount: 475, token });
  // Asking "did you get it?" of someone the CRM watched open the page reads
  // as not paying attention, which is the opposite of the intended effect.
  chk("the two nudges say different things", unopened !== opened);
  chk("neither nudge is UCS-2", M.segmentsFor(unopened).encoding === "GSM-7" && M.segmentsFor(opened).encoding === "GSM-7");
  for (const [name, text] of [["unopened", unopened], ["opened", opened]]) {
    chk(`the ${name} nudge offers an opt-out`, /reply stop/i.test(text));
  }

  const reminder = M.reminderSms({
    customerName: "Marilyn Hollingsworth",
    // 9am Pacific, expressed in UTC so the test does not depend on the
    // machine's own timezone.
    startsAt: "2026-09-22T16:00:00Z",
  });
  chk("the reminder states the time in Oregon time", reminder.includes("9:00"), reminder);
  chk("the reminder is GSM-7", M.segmentsFor(reminder).encoding === "GSM-7");
  chk("the reminder offers an opt-out", /reply stop/i.test(reminder));
}

// --- E.164, which must agree with the database ------------------------------
{
  chk("a formatted number normalises", M.toE164("(541) 730-3593") === "+15417303593");
  chk("a leading 1 is not doubled", M.toE164("1-541-730-3593") === "+15417303593");
  chk("a short number is null", M.toE164("541-730-359") === null);
  chk("an impossible area code is null", M.toE164("(041) 730-3593") === null);
  chk("empty is null, not a crash", M.toE164("") === null && M.toE164(null) === null);
}

// --- the mode switch --------------------------------------------------------
{
  const was = process.env.SMS_MODE;

  delete process.env.SMS_MODE;
  chk("THE POINT: with nothing configured, texting is off", M.smsMode() === "off", M.smsMode());

  process.env.SMS_MODE = "SEND";
  chk("the mode is case-insensitive", M.smsMode() === "send");

  process.env.SMS_MODE = "yes-please";
  chk("an unrecognised mode falls back to off, not to send", M.smsMode() === "off", M.smsMode());

  process.env.SMS_MODE = "off";
  chk(
    "nothing is sent while the mode is off",
    (await M.sendSms({ phone: "(541) 730-3593", body: "hi" })).reason === "sms_off"
  );

  process.env.SMS_MODE = "preview";
  const previewed = await M.sendSms({ phone: "(541) 730-3593", body: "hi" });
  chk("preview reports what would go without claiming it", previewed.reason === "preview" && previewed.preview?.body === "hi");

  // THE POINT. The claim talks to the database, and rpc() THROWS on a database
  // error. Unwrapped, a missing claim_sms — which is just "db/sms.sql has not
  // been run yet" — escaped sendSms and 500'd the whole /api/send-quote
  // request: no quote saved, no link returned, the entire feature taken down
  // by a failure to send a text. Sending a text is the last and least
  // important thing that request does.
  process.env.SMS_MODE = "send";
  process.env.QUO_API_KEY = "test-key";
  process.env.QUO_FROM = "+15417303593";

  // Exactly what PostgREST says when the migration has not been run.
  globalThis.__rpc = async () => {
    throw new Error(
      "Could not find the function public.claim_sms(p_body, p_customer_id, p_force, p_job_id, p_kind, p_lead_id, p_phone, p_quote_id, p_sent_by) in the schema cache"
    );
  };

  const missing = await M.sendSms({ phone: "(541) 730-3593", body: "hi" });
  chk(
    "THE POINT: a database failure is reported, not thrown",
    missing.ok === false,
    JSON.stringify(missing)
  );
  chk(
    "and a missing migration names itself",
    missing.reason === "no_sms_tables",
    missing.reason
  );

  // Any other database failure comes back with its own message rather than
  // being flattened into one unhelpful sentence.
  globalThis.__rpc = async () => {
    throw new Error("permission denied for function claim_sms");
  };
  const denied = await M.sendSms({ phone: "(541) 730-3593", body: "hi" });
  chk(
    "another database failure keeps its own message",
    denied.ok === false && /permission denied/.test(denied.reason),
    denied.reason
  );

  // And a refusal from the database itself — an opt-out, quiet hours — is
  // passed straight through as the reason the screen shows.
  globalThis.__rpc = async () => [{ id: null, ok: false, reason: "opted_out", phone: "+15417303593" }];
  const stopped = await M.sendSms({ phone: "(541) 730-3593", body: "hi" });
  chk("a refusal carries its reason to the screen", stopped.reason === "opted_out", stopped.reason);

  delete globalThis.__rpc;
  delete process.env.QUO_API_KEY;
  delete process.env.QUO_FROM;

  if (was === undefined) delete process.env.SMS_MODE;
  else process.env.SMS_MODE = was;
}

console.log(bad === 0 ? "\nSMS helpers hold" : `\n${bad} failure(s)`);
process.exitCode = bad === 0 ? 0 : 1;
